### ISSUE TITLE
Anmelden

### ISSUE THREAD

**Issue by Malingmax** [K0NRAD/food-control-001#13]
Als Benutzer möchte ich mich anmelden können, um auf meine gespeicherten Inhalte zurückgreifen zu können.

**Akzeptanzkriterien**
- Registrierung
- Anwender müssen explizit berechtigt werden die Anwendung zu nutzen.

**Comment by Aragur** [comment]
`Anwender müssen explizit berechtigt werden die Anwendung zu nutzen.`  
Soll der Admin hier im UI eine Liste mit den Nutzern sehen, und diese dann manuell aktivieren / deaktivieren können?

**Comment by Aragur** [comment]
@Malingmax @Norowa  bitte Follow Up Ticket für die Aktivierung der Nutzeraccounts via Admin
